name: Fav.sh CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [13.8.0]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
      run: npm install -g yarn
      run: yarn
      
      - name: Typecheck
      run: yarn tsc

      - name: Prettier
      run: yarn format

      env:
        ci: TRUE